---
- hosts: localhost
  tasks:

  - name: Enable udev rules
    become: true
    lineinfile:
      name: /etc/udev/rules.d/91-usbip-server-tools.rules
      create: yes
      state: present
      line: SUBSYSTEM=="usb" ATTRS{idVendor}!="1781" RUN+="/usr/sbin/usbip bind -b $kernel"
