---
- hosts: localhost
  tasks:

  - name: Enable udev rules
    become: true
    lineinfile:
      path: /etc/udev/rules.d/91-usbip-server-tools.rules
      create: yes
      state: present
      line: SUBSYSTEM=="usb" ATTRS{idVendor}=="1781" ATTRS{idProduct}=="0c9f" RUN+="/usr/bin/usbip bind -b $kernel"
