---
- hosts: localhost
  vars:
    vm_ip: "{{ip}}"
    ssh_port: "{{ (vm_ip | int) + 7000}}"
    usbip_port: "{{ (vm_ip | int) + 6000}}"
  tasks:

  - name: Install autossh
    become: true
    apt:
      name: autossh
      state: present

  - name: Update ssh tunnel service file
    become: true
    lineinfile:
      name: /etc/rc.local
      state: present
      line: sleep 240 &&  /usr/bin/autossh -i /usr/local/bin/ACG-USBIP-pi/id_rsa -T -f -N  tunnel@ece477-vcl.acg.maine.edu -R {{ssh_port}}:localhost:22
  - name: Update usbip tunnel service file
    become: true
    lineinfile:
      name: /etc/rc.local
      state: present
      line: sleep 240 && /usr/bin/autossh  -i /usr/local/bin/ACG-USBIP-pi/id_rsa -T -f -N  tunnel@ece477-vcl.acg.maine.edu -R {{usbip_port}}:localhost:3240
